version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: test123
      MYSQL_PASSWORD: test123
      MYSQL_DATABASE: demo_tools_produect
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  db_data:
